language: python

env:
  global:
    - NODE_VERSION=12.18
    - ARTIFACT_BUCKET=okty-artifacts

services:
  - docker

install:
  - docker run -v $(PWD):/app -w /app node:$(NODE_VERSION) npm install

script:
  - docker run -v $(PWD):/app -w /app node:$(NODE_VERSION) npm run test

before_deploy:
  - rm -rf ./__tests__
  - docker run -v $(PWD):/app -w /app node:$(NODE_VERSION) npm prune --production
  - pip install awscli aws-sam-cli
  - sam validate

deploy:
  provider: script
  script:
    - "return 0;"
#    - sam package
#    - sam deploy
