language: bash

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.sonar

services:
    - docker

before_install:
    - cp .env.dist .env

install:
    - docker run -v $(pwd):/app -v $HOME/.composer/cache:/tmp composer:1.8 install

script:
    - docker run -v $(pwd):/app -w /app phpunit/phpunit -c phpunit.xml.dist
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker run -v $PWD:/usr/src -v $HOME/.sonar:/root/.sonar -e SONAR_TOKEN=$SONAR_TOKEN newtmitch/sonar-scanner:4.0 ; fi

deploy:
    -   provider: heroku
        api_key:
            secure: N1zHPTFpF7pdYh3dUkgXmQb0bJj4qjIc89HRVQF4TzZwZYc4/a60svyaQX61fje1lLC9ezsW+iM7eAuq+ptsyfa3bNAlzXKrTgqUmmaIoAeIlEF3i5bGiHjD8PpByHqNy4nbOqKYy9Uym/yKiW7qutegt7lktFOA9G40xpVs9ICenX9H5MFVGRDfTkzQQ5ZPfF9r6hhysMzLVnuLPBlfcszRlWVixcZ6DMzHJCXImxiHqySAErAhPVzQPJH8cPTaidslhTQNfL+N5amwB67WzH0iw3Dzjs0ICJgQlXdkIWAi8gI6OFIdeNuzcWhCIFg29z6GIbP5qmEKSF2PIqsmIQqtYa71JEhSdlCstaxcaHbX9sEKz3+7G9hFP0mXt+JDWwcr3LBt3wQD4+jkRJU2dM76XbkGJW3AwewARzmOFOJrPgF7JCzAQ344Z2VvsNyWdl5idQDPwg5tMXbWJ8nKr7ozH4EyQWs8snaKsEiM2uxrSdgmgFcwKrajnAjFV8B3BNhYHQRYDw3dcvSFSWmAvxkeq6A2h7SmNJxRW6VVICoMeQYxaB4Go+SPZeWqKoL2pAnNug8QD2E7a7+JNy6rWqYlYlLC6xK9djR2Nz4wM+ONYK17mffpOOlcoJHursIzvssbwiv+c8T16ei3riKit0pu2XXriXZ3nzxug3CdRzY=
        app: okty-server
        on:
            repo: Okty-io/okty-server
            branch: master
    -   provider: heroku
        api_key:
            secure: N1zHPTFpF7pdYh3dUkgXmQb0bJj4qjIc89HRVQF4TzZwZYc4/a60svyaQX61fje1lLC9ezsW+iM7eAuq+ptsyfa3bNAlzXKrTgqUmmaIoAeIlEF3i5bGiHjD8PpByHqNy4nbOqKYy9Uym/yKiW7qutegt7lktFOA9G40xpVs9ICenX9H5MFVGRDfTkzQQ5ZPfF9r6hhysMzLVnuLPBlfcszRlWVixcZ6DMzHJCXImxiHqySAErAhPVzQPJH8cPTaidslhTQNfL+N5amwB67WzH0iw3Dzjs0ICJgQlXdkIWAi8gI6OFIdeNuzcWhCIFg29z6GIbP5qmEKSF2PIqsmIQqtYa71JEhSdlCstaxcaHbX9sEKz3+7G9hFP0mXt+JDWwcr3LBt3wQD4+jkRJU2dM76XbkGJW3AwewARzmOFOJrPgF7JCzAQ344Z2VvsNyWdl5idQDPwg5tMXbWJ8nKr7ozH4EyQWs8snaKsEiM2uxrSdgmgFcwKrajnAjFV8B3BNhYHQRYDw3dcvSFSWmAvxkeq6A2h7SmNJxRW6VVICoMeQYxaB4Go+SPZeWqKoL2pAnNug8QD2E7a7+JNy6rWqYlYlLC6xK9djR2Nz4wM+ONYK17mffpOOlcoJHursIzvssbwiv+c8T16ei3riKit0pu2XXriXZ3nzxug3CdRzY=
        app: okty-server-dev
        on:
            repo: Okty-io/okty-server
            branch: dev
