language: python

env:
  global:
    - NODE_VERSION=12.18
    - ARTIFACT_BUCKET=okty-artifacts

services:
  - docker

install:
  - docker run -v ${TRAVIS_BUILD_DIR}:/app -w /app node:${NODE_VERSION} npm install

script:
  - docker run -v ${TRAVIS_BUILD_DIR}:/app -w /app node:${NODE_VERSION} npm run test

before_deploy:
  - rm -rf ./__tests__
  - docker run -v ${TRAVIS_BUILD_DIR}:/app -w /app node:${NODE_VERSION} npm prune --production
  - pip install awscli aws-sam-cli
  - sam validate

deploy:
  provider: script
  script: |
    sam package --s3-bucket ${ARTIFACT_BUCKET} --output-template-file generated.yml
    sam deploy --template-file generated.yml --stack-name okty-builder
  on:
    all_branches: true
