version: '3.6'
services:
    db:
        image: 'mariadb:10.3'
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        volumes:
            - 'database:/var/lib/mysql'
        networks:
            - okty-api
    php:
        build: 'docker/php'
        volumes:
            - './:/usr/share/nginx/html'
        working_dir: '/usr/share/nginx/html'
        networks:
            - okty-api
    nginx:
        build: 'docker/nginx'
        environment:
            - MAX_UPLOAD_SIZE=2M
            - PHP_CONTAINER_ID=php
            - INDEX_SUBFOLDER=public
        volumes:
            - './:/usr/share/nginx/html'
        ports:
            - '8080:80'
        networks:
            - okty-api
    adminer:
        image: 'adminer:4.7'
        networks:
            - okty-api
        ports:
            - '8081:8080'
    redis:
        image: redis:4.0.2
        hostname: redis
        networks:
            - okty-api

volumes:
    database: ~

networks:
    okty-api:
        name: okty-api
