version: '3.3'
services:
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: okty
        ports:
            - "127.0.0.1:3342:3306"
        volumes:
            - database:/var/lib/mysql

    app:
        image: nginx:alpine
        volumes:
            - .:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "127.0.0.1:8042:80"

    php:
        build: ./docker/php
        user: php
        working_dir: /app
        volumes:
            - .:/app

    redis:
        image: redis:4.0.2
        hostname: redis

volumes:
    database: ~
