version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "okty"
s3_bucket = "okty-artifacts"
s3_prefix = "okty"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

